### ISSUE TITLE
Image::convertToBufferedImage is indeterministic

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusInterfaces#4]
This behavior seems to result from ImageIO internals and can be reproduced with images where only specific readers (from those that claim to be able to read the source) work as expected, e.g. on JPEG compressed images with "tif" filename extensions. See eu.transkribus.interfaces.types.ImageTest::testFromUrlToBufferedImage

Findings so far:
- ImageIO registers Reader/Writer plugins internally in a HashMap and the order of the entry set may thus change over time
- ImageIO::read iterates readers, takes the first one that returns true when calling ImageReaderSpi::.canDecodeInput and if the actual read operation fails throws an IIOException
- IIORegistry::register returns false if a reader of the given type is already registered, according to its JavaDoc. BUT: acutally it deregisters the old instance and puts the new instance into the map, altering the order of the entry set. Subsequent registering of the same plugin will therefore change the behavior of ImageIO::read for certain images.

Steps taken so far:
- Image type does not contain a static block registering Readers and Writers anymore. This was needed by web applications in Tomcat so far but is solved with a context listener that registers plugins on the classpath automatically.
- ImageUtils has an alternative implementation of ImageIO::read that tries other candidate-readers first if one reader fails.

**Comment by kahlep** [comment]
Alternate implementation of ImageIO::read may fail on images where orginal impl works. The same scheme could be applied and tested when creating the ImageInputStream object. Also seems to depend on the Version of JRE version used. Sometimes reading jpg images with Jdk1.8.0_102 works, in other cases only with Jdk1.8.0_121 (confirmed for BenthamClean set).
Next try could use original implementation and alternative only if null is returned from first try.

**Comment by kahlep** [comment]
Issue might be related to incompatibilities between JAI and the twelvemonkes ImageIO plugins. See https://github.com/haraldk/TwelveMonkeys/issues/433
In ImageUtils this might happen when the JAI plugin is picked for reading the TIFF, but the twelvemonkeys plugin is picked for reading the contained JPEG:
```
javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:762)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:334)
	at com.sun.media.imageioimpl.plugins.tiff.TIFFJPEGDecompressor.decodeRaw(TIFFJPEGDecompressor.java:224)
	at com.sun.media.imageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2527)
	at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1137)
	at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1417)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
```

**Comment by kahlep** [comment]
Relying only on the twelvemonkeys ImageIO impl for now. Interoperability with JAI seems to be fixed in version 3.4 of the lib though.
